# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20161011_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='update date'),
        ),
    ]
